service: greetingsvc

provider:
  name: aws
  runtime: python3.6

functions:
  get-greeting:
    handler: handler.get_greeting
    events:
      - http:
          path: get/greeting
          method: get
  post-greeting:
    handler: handler.post_greeting
    events:
      - http:
          path: post/greeting
          method: post

plugins:
  - serverless-plugin-simulate
  - serverless-python-requirements
